Repository jenkinsci/avatar-plugin, pull requests merged in 2025-02, with the labels that each got.

#4 Refresh plugin for 2025
  .github/CODEOWNERS
  .github/renovate.json
  .github/workflows/cd.yaml
  .gitignore
  .mvn/extensions.xml
  .mvn/maven.config
  Jenkinsfile
  LICENSE
  README.md
  docs/avatar-example.png
  pom.xml
  src/main/java/net/hurstfrost/jenkins/avatar/user/AvatarProperty.java
  src/main/java/net/hurstfrost/jenkins/avatar/user/AvatarResolver.java
  src/main/resources/index.jelly
  src/main/resources/net/hurstfrost/jenkins/avatar/user/AvatarProperty/config.jelly
  src/main/resources/net/hurstfrost/jenkins/avatar/user/AvatarProperty/configIframe.jelly
  src/main/resources/net/hurstfrost/jenkins/avatar/user/AvatarProperty/summary.jelly
  src/main/webapp/checker16x16.png
  src/main/webapp/css/avatar.css
  src/main/webapp/js/avatar.js
Labels: enhancement

#6 Fix documentation URL
  pom.xml
Labels: enhancement

#7 Save avatar to disk instead of as bytes in XML
  pom.xml
  src/main/java/net/hurstfrost/jenkins/avatar/user/AvatarProperty.java
Labels: enhancement

#10 Allow other avatar resolvers to work with this plugin
  src/main/java/net/hurstfrost/jenkins/avatar/user/AvatarResolver.java
Labels: enhancement

#11 Raise priority of this plugin in resolving avatars
  src/main/java/net/hurstfrost/jenkins/avatar/user/AvatarResolver.java
Labels: enhancement

#12 Add tests
  src/test/java/net/hurstfrost/jenkins/avatar/user/AvatarPropertyTest.java
  src/test/java/net/hurstfrost/jenkins/avatar/user/AvatarResolverTest.java
  src/test/java/net/hurstfrost/jenkins/avatar/user/UITest.java
  src/test/java/net/hurstfrost/jenkins/avatar/user/util/MockRequest.java
  src/test/java/net/hurstfrost/jenkins/avatar/user/util/MockResponse.java
  src/test/resources/avatar.png
Labels: tests

#17 Add databound constructor
  src/main/java/net/hurstfrost/jenkins/avatar/user/AvatarProperty.java
Labels: bug
